###consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  ####consul注册中心地址
  cloud:
    consul:
      host: 101.200.210.117
      port: 8500
#      discovery:
#        #        hostname: 101.200.210.117
#        service-name: ${spring.application.name}
#        prefer-ip-address: true
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true   # 表示注册时使用IP而不是hostname
        enabled: true       # 启用服务发现
        register: true      # 启用服务注册
        deregister: true    # 表示停止时取消注册
        register-health-check: false
#        health-check-interval: 10s            # 健康检查频率
#        health-check-critical-timeout: 30s    # 健康检查失败多长时间后，取消注册
#        health-check-path: /actuator/health   # 健康检查路径

