###consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  ####consul注册中心地址
  cloud:
    consul:
      host: 101.200.210.117
      port: 8500
      discovery:
#        hostname: 222.221.237.140
        service-name: ${spring.application.name}
        prefer-ip-address: true
#        prefer-agent-address: true
#        ip-address: 222.221.237.140



