###consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  ####consul注册中心地址
  cloud:
    consul:
      host: 101.200.210.117
      port: 8500
      discovery:
#        hostname: localhost
        service-name: ${spring.application.name}



