###consul服务端口号
server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  ####consul注册中心地址
  cloud:
    consul:
      host: 101.200.210.117
      port: 8500
      discovery:
        hostname: 172.21.80.91
        service-name: ${spring.application.name}

