server:
  port: 20002

spring:
  application:
    name: seata-storage-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: 101.200.210.117:11111
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://101.200.210.117:23306/seata_storage
    username: seata
    password: seata

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


