server:
  port: 80
#debug: true

spring:
  application:
    name: cloud-consumer-order
  cloud:
    #注册到zookeeper地址
    zookeeper:
      connect-string: 101.200.210.117:2181
#    loadbalancer:
#      ribbon:

#        enabled: false