server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TzashiNorpu/SpringCloudConfig.git #GitHub上面的git仓库名字
          ####搜索目录 可以找到不在当前根目录下的文件
          search-paths:
            - SpringCloudConfig
          # http://config3344.com:3344/SpringCloudConfig/tree/master/test/test2/config-test.yml ? 这个可以访问到文件，但是返回的格式不一样
          password: yanggumaji74520
          username: TzashiNorpu@gmail.com
          ####读取分支
#          http://config3344.com:3344/master/config-dev.yml(默认使用label指定的分支)和这个http://config3344.com:3344/config-dev.yml都可以
      label: master

  #rabbitmq相关配置
  rabbitmq:
    host: 101.200.210.117
    port: 20000
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

  ##rabbitmq相关配置,暴露bus刷新配置的端点

#
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'


